### ISSUE TITLE
Service & Facade layer for TeamPlayer

### ISSUE THREAD

**Issue by 396507** [fprochazka/fi-muni-PA165-project#40]
## Aplikace
* [x] Předělat DAO na Repository
* [x] Veškerou logiku přenést do 'TeamPlayerService'
* [x] Založit 'TeamPlayerFacade', která bude řídit transakce a persistenci

## TeamPlayerRepository
- getPlayerById
- findPlayerByFirstname
- findPlayerBySurname
- findPlayerByTeam
- findAllPlayers

## TeamPlayerService
- createPlayer
- changeFirstname
- changeSurname
- changeHeight
- changeWeight

## TeamPlayerFacade
- createPlayer
- deletePlayer
- changeFirstname
- changeSurname
- changeHeight
- changeWeight

**Comment by denis-galajda** [comment]
add methods to change Team of TeamPlayer
